config/routes.rb
Rails.application.routes.draw do
  resources :monuments
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monument.rb
class Monument < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  before_action :set_monument, only: %i[ show edit update destroy ]

  # GET /monuments
  def index
    @monuments = Monument.all
    @monument = Monument.new
  end

  # GET /monuments/1
  def show
  end

  # GET /monuments/new
  def new
    @monument = Monument.new
  end

  # GET /monuments/1/edit
  def edit
  end

  # POST /monuments
  def create
    @monument = Monument.new(monument_params)

    if @monument.save
      redirect_to @monument, notice: "Monument was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /monuments/1
  def update
    if @monument.update(monument_params)
      redirect_to @monument, notice: "Monument was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /monuments/1
  def destroy
    @monument.destroy
    redirect_to monuments_url, notice: "Monument was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monument
      @monument = Monument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monument_params
      params.require(:monument).permit(:name, :address, :opening_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JavascriptInRails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monuments/_form.html.erb
<%= simple_form_for(monument) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :opening_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/monuments/_monument.html.erb
<div id="<%= dom_id monument %>">
  <p>
    <strong>Name:</strong>
    <%= monument.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <span data-controller="typed"
          data-typed-sentences-value="<%= [monument.address].to_json %>">
    </span>
  </p>

  <p>
    <strong>Opening date:</strong>
    <%= monument.opening_date %>
  </p>

</div>

app/views/monuments/edit.html.erb
<h1>Editing monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Show this monument", @monument %> |
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <p style="color: green"><%= notice %></p>

      <h1>Monuments</h1>

      <div id="monuments">
        <% @monuments.each do |monument| %>
          <%= render monument %>
          <p>
            <%= link_to "Show this monument", monument %>
          </p>
        <% end %>
      </div>

      <div data-controller='toggle' class='mt-5'>
        <button class="btn btn-outline-primary mb-3" data-action="click->toggle#fire" > Add a new monument</button>
        <div data-toggle-target="togglableElement" class="d-none">
          <%= render "form", monument: @monument %>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/monuments/new.html.erb
<h1>New monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @monument %>

<div>
  <%= link_to "Edit this monument", edit_monument_path(@monument) %> |
  <%= link_to "Back to monuments", monuments_path %>

  <%= button_to "Destroy this monument", @monument, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>